/*---------------------------------------------------------------------------*\
                                                                             
  FILE........: cohpsk_put_test_bits.c
  AUTHOR......: David Rowe  
  DATE CREATED: April 2015
                                                                             
  Sinks a stream of test bits generated by cohpsk_get_test_bits, useful for 
  testing coh psk mod and demod.

\*---------------------------------------------------------------------------*/


/*
  Copyright (C) 2015 David Rowe

  All rights reserved.

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License version 2, as
  published by the Free Software Foundation.  This program is
  distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or
  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
  License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with this program; if not, see <http://www.gnu.org/licenses/>.
*/

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <errno.h>

#include "codec2_cohpsk.h"
#include "test_bits_coh.h"

int main(int argc, char *argv[])
{
    FILE         *fin;
    int           rx_bits[COHPSK_BITS_PER_FRAME];
    int           *ptest_bits_coh, *ptest_bits_coh_end;
    int           state, next_state, i, nbits, nerrors;
    float         corr;

    if (argc < 2) {
	printf("usage: %s InputOneBitPerIntFile\n", argv[0]);
	exit(1);
    }

    if (strcmp(argv[1], "-") == 0) fin = stdin;
    else if ( (fin = fopen(argv[1],"rb")) == NULL ) {
	fprintf(stderr, "Error opening input file: %s: %s.\n",
         argv[1], strerror(errno));
	exit(1);
    }

    ptest_bits_coh = (int*)test_bits_coh;
    ptest_bits_coh_end = (int*)test_bits_coh + sizeof(test_bits_coh)/sizeof(int);

    while (fread(rx_bits, sizeof(int), COHPSK_BITS_PER_FRAME, fin) ==  COHPSK_BITS_PER_FRAME) {

        corr = 0.0;
        for(i=0; i<COHPSK_BITS_PER_FRAME; i++) {
            corr += (1.0 - 2.0*(rx_bits[i] & 0x1)) * (1.0 - 2.0*ptest_bits_coh[i]);
        }

        /* state logic */

        next_state = state;

        if (state == 0) {
            fprintf(stderr, "corr %f\n", corr);            
            if (corr == COHPSK_BITS_PER_FRAME) {
                next_state = 1;
                ptest_bits_coh += COHPSK_BITS_PER_FRAME;
                nerrors = COHPSK_BITS_PER_FRAME - corr;
                nbits = COHPSK_BITS_PER_FRAME;
            }
        }

        if (state == 1) {
            nerrors += COHPSK_BITS_PER_FRAME - corr;
            nbits   += COHPSK_BITS_PER_FRAME;
            ptest_bits_coh += COHPSK_BITS_PER_FRAME;
            if (ptest_bits_coh >= ptest_bits_coh_end) {
                ptest_bits_coh = (int*)test_bits_coh;
            }
        }

        state = next_state;

        if (fin == stdin) fflush(stdin);
    }

    fclose(fin);
    printf("BER: %3.2f Nbits: %d Nerrors: %d\n", (float)nerrors/nbits, nbits, nerrors);

    return 0;
}

