/*---------------------------------------------------------------------------*\

  FILE........: ofdm_demod.c
  AUTHOR......: David Rowe
  DATE CREATED: Mar 2018

  Given an input file of raw file (8kHz, 16 bit shorts) of OFDM modem
  samples.  Optionally outputs one char per bit (hard decision), or
  soft decision rx_np and rx_amp QPSK symbols information for LDPC decoder.

\*---------------------------------------------------------------------------*/

/*
  Copyright (C) 2018 David Rowe

  All rights reserved.

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License version 2, as
  published by the Free Software Foundation.  This program is
  distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or
  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
  License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with this program; if not, see <http://www.gnu.org/licenses/>.
*/

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <errno.h>

#include "codec2_ofdm.h"
#include "ofdm_internal.h"
#include "octave.h"
#include "test_bits_ofdm.h"
#include "mpdecode_core.h"
#include "gp_interleaver.h"

#define ASCALE   (2E5*1.1491/2.0) /* scale from shorts back to floats     */
#define NFRAMES  100              /* just log the first 100 frames        */
#define NDISCARD 20               /* BER2measure disctrds first 20 frames */
#define CODED_BITSPERFRAME 224    /* number of LDPC codeword bits/frame   */

#include "HRA_112_112.h"          /* generated by ldpc_fsk_lib.m:ldpc_decode() */
#define CODED_BITSPERFRAME 224    /* number of LDPC codeword bits/frame   */

int opt_exists(char *argv[], int argc, char opt[]) {
    int i;
    for (i=0; i<argc; i++) {
        if (strcmp(argv[i], opt) == 0) {
            return i;
        }
    }
    return 0;
}

int main(int argc, char *argv[])
{
    FILE          *fin, *fout, *foct;
    struct OFDM   *ofdm;
    int            nin_frame;

    float          phase_est_pilot_log[OFDM_ROWSPERFRAME*NFRAMES][OFDM_NC];
    COMP           rx_np_log[OFDM_ROWSPERFRAME*OFDM_NC*NFRAMES];
    float          rx_amp_log[OFDM_ROWSPERFRAME*OFDM_NC*NFRAMES];
    float          foff_hz_log[NFRAMES];
    int            timing_est_log[NFRAMES];

    int            i, j, f, oct, logframes, arg, llr_en;
    int            Nerrs, Terrs, Tbits, Terrs2, Tbits2, testframes, frame_count;
    
    struct LDPC   ldpc;
    ldpc.max_iter = HRA_112_112_MAX_ITER;
    ldpc.dec_type = 0;
    ldpc.q_scale_factor = 1;
    ldpc.r_scale_factor = 1;
    ldpc.CodeLength = HRA_112_112_CODELENGTH;
    ldpc.NumberParityBits = HRA_112_112_NUMBERPARITYBITS;
    ldpc.NumberRowsHcols = HRA_112_112_NUMBERROWSHCOLS;
    ldpc.max_row_weight = HRA_112_112_MAX_ROW_WEIGHT;
    ldpc.max_col_weight = HRA_112_112_MAX_COL_WEIGHT;
    ldpc.H_rows = HRA_112_112_H_rows;
    ldpc.H_cols = HRA_112_112_H_cols;

    if (argc < 3) {
        fprintf(stderr, "\n");
	printf("usage: %s InputModemRawFile OutputFile [-o OctaveLogFile] [--llr] [-v VerboseLevel]\n", argv[0]);
        fprintf(stderr, "\n");
        fprintf(stderr, "              Default output file format is one byte per bit hard decision\n");
        fprintf(stderr, "  -t          Receive test frames and count errors\n");
        fprintf(stderr, "  -v          Verbose info the stderr\n");
        fprintf(stderr, "  -o          Octave log file for testing\n");
        fprintf(stderr, "  --llr       LLR output, one double per bit, %d doubles/frame\n", CODED_BITSPERFRAME);
        fprintf(stderr, "\n");
	exit(1);
    }

    if (strcmp(argv[1], "-")  == 0) fin = stdin;
    else if ( (fin = fopen(argv[1],"rb")) == NULL ) {
	fprintf(stderr, "Error opening input modem sample file: %s: %s.\n",
         argv[1], strerror(errno));
	exit(1);
    }

    if (strcmp(argv[2], "-") == 0) fout = stdout;
    else if ( (fout = fopen(argv[2],"wb")) == NULL ) {
	fprintf(stderr, "Error opening output file: %s: %s.\n",
         argv[2], strerror(errno));
	exit(1);
    }

    foct = NULL;
    oct = 0;
    if ((arg = opt_exists(argv, argc, "-o")) != 0) {
        if ( (foct = fopen(argv[arg+1],"wt")) == NULL ) {
            fprintf(stderr, "Error opening output Octave file: %s: %s.\n",
                    argv[4], strerror(errno));
	exit(1);
        }
        oct = 1;
        logframes = NFRAMES;
    }

    llr_en = 0;
    if (opt_exists(argv, argc, "--llr")) {
        llr_en = 1;
    }

    testframes = 0;
    if (opt_exists(argv, argc, "-t")) {
        testframes = 1;
    }

    ofdm = ofdm_create(OFDM_CONFIG_700D);
    assert(ofdm != NULL);

    if ((arg = opt_exists(argv, argc, "-v")) != 0) {
        ofdm_set_verbose(ofdm, atoi(argv[arg+1]));
    }

    int Nbitsperframe = ofdm_get_bits_per_frame(ofdm);
    int Nmaxsamperframe = ofdm_get_max_samples_per_frame();
    
    short  rx_scaled[Nmaxsamperframe];
    COMP   rxbuf_in[Nmaxsamperframe];
    int    rx_bits[Nbitsperframe];
    char   rx_bits_char[Nbitsperframe];
    int    rx_uw[OFDM_NUWBITS];
    f = 0; Nerrs = Terrs = Tbits = Terrs2 = Tbits2 = frame_count = 0;

    float EsNo = 10;
    fprintf(stderr,"Warning EsNo: %f hard coded", EsNo);

    nin_frame = ofdm_get_nin(ofdm);
    while(fread(rx_scaled, sizeof(short), nin_frame, fin) == nin_frame) {

	/* scale and demod */

	for(i=0; i<nin_frame; i++) {
	    rxbuf_in[i].real = (float)rx_scaled[i]/ASCALE;
            rxbuf_in[i].imag = 0.0;
        }

        if (strcmp(ofdm->sync_state,"searching") == 0) {
            ofdm_sync_search(ofdm, rxbuf_in);
        }
    
        if ((strcmp(ofdm->sync_state,"synced") == 0) || (strcmp(ofdm->sync_state,"trial_sync") == 0) ) {
            ofdm_demod(ofdm, rx_bits, rxbuf_in);
            
            if (llr_en) {
                double symbol_likelihood[ (CODED_BITSPERFRAME/OFDM_BPS) * (1<<OFDM_BPS) ];
                double bit_likelihood[CODED_BITSPERFRAME];
                double llr[CODED_BITSPERFRAME];

                /* first few symbols are used for UW and txt bits, find start of (224,112) LDPC codeword */

                assert((OFDM_NUWBITS+OFDM_NTXTBITS+CODED_BITSPERFRAME) == OFDM_BITSPERFRAME);

                COMP ldpc_codeword_symbols[CODED_BITSPERFRAME/OFDM_BPS];
                for(i=0, j=(OFDM_NUWBITS+OFDM_NTXTBITS)/OFDM_BPS; i<(CODED_BITSPERFRAME/OFDM_BPS); i++,j++) {
                    ldpc_codeword_symbols[i].real = crealf(ofdm->rx_np[j]);
                    ldpc_codeword_symbols[i].imag = cimagf(ofdm->rx_np[j]);
                }
                float *ldpc_codeword_symbol_amps = &ofdm->rx_amp[(OFDM_NUWBITS+OFDM_NTXTBITS)/OFDM_BPS];

                COMP codeword_symbols_de[CODED_BITSPERFRAME/OFDM_BPS];
                float codeword_amps_de[CODED_BITSPERFRAME/OFDM_BPS];

                gp_interleave_comp(codeword_symbols_de, ldpc_codeword_symbols, CODED_BITSPERFRAME/OFDM_BPS);
                gp_interleave_float(codeword_amps_de, ldpc_codeword_symbol_amps, CODED_BITSPERFRAME/OFDM_BPS);
                
                Demod2D(symbol_likelihood, codeword_symbols_de, S_matrix, EsNo, codeword_amps_de,  CODED_BITSPERFRAME/OFDM_BPS);
                Somap(bit_likelihood, symbol_likelihood, CODED_BITSPERFRAME/OFDM_BPS);
                for(i=0; i<CODED_BITSPERFRAME; i++) {
                    llr[i] = -bit_likelihood[i];
                }
                
                int    iter;
                char   out_char[CODED_BITSPERFRAME];
                int    parityCheckCount;
                
                for(i=0; i<CODED_BITSPERFRAME; i++) {
                    llr[i] = -bit_likelihood[i];
                }

                int ldpc_en = 1;
                if (ldpc_en) {
                    /* run LDPC decoder and output decoded bits */
                    /* TODO
                       [ ] how to test uncoded modem, maybe use LDPC encoded frame?
                       [ ] log unsucessfully decoded frames, outout them anyway?
                     */
                    
                    iter = run_ldpc_decoder(&ldpc, out_char, llr, &parityCheckCount);
                    #ifdef TODO
                    if (testframes) {
                        /* measure raw and coded BER */
                        Terrs += Nerrs;
                        Tbits += Nbitsperframe;
                    }
                    
                    if (frame_count >= NDISCARD) {
                        Terrs2 += Nerrs;
                        Tbits2 += Nbitsperframe;
                    }
                    #endif
                }
                
                fprintf(stderr, "iter: %d parityCheckCount: %d\n", iter, parityCheckCount);

                fwrite(llr, sizeof(double), CODED_BITSPERFRAME, fout);

            } else {
                /* simple hard decision output for uncoded testing, all bits in frame dumped inlcuding UW and txt */
                for(i=0; i<Nbitsperframe; i++) {
                    rx_bits_char[i] = rx_bits[i];
                }
                fwrite(rx_bits_char, sizeof(char), Nbitsperframe, fout);
            }

            /* extract Unique Word bits */

            for(i=0; i<OFDM_NUWBITS; i++) {
                rx_uw[i] = rx_bits[i];
            }

            /* optional error counting in testframe mode */
            
            if (testframes) {
                Nerrs = 0;
                for(i=0; i<Nbitsperframe; i++) {
                    if (test_bits_ofdm[i] != rx_bits[i]) {
                        Nerrs++;
                    }
                }

                Terrs += Nerrs;
                Tbits += Nbitsperframe;

                if (frame_count >= NDISCARD) {
                    Terrs2 += Nerrs;
                    Tbits2 += Nbitsperframe;
                }
            }
            frame_count++;
        }
        
        nin_frame = ofdm_get_nin(ofdm);
        ofdm_sync_state_machine(ofdm, rx_uw);

        /* act on any events returned by state machine */
    
        if (ofdm->sync_start) {
            Terrs = Tbits = Terrs2 = Tbits2 = frame_count = 0;
        }

        if (ofdm->verbose) {
            fprintf(stderr, "f: %2d state: %-10s uw_errors: %2d %1d  Nerrs: %3d foff: %3.1f\n",
                    f, ofdm->last_sync_state, ofdm->uw_errors, ofdm->sync_counter, Nerrs, ofdm->foff_est_hz);
        }

        /* optional logging of states */
        
        if (oct) {
            /* note corrected phase (rx no phase) is one big linear array for frame */

            for (i = 0; i < OFDM_ROWSPERFRAME*OFDM_NC; i++) {
                rx_np_log[OFDM_ROWSPERFRAME*OFDM_NC*f + i].real = crealf(ofdm->rx_np[i]);
                rx_np_log[OFDM_ROWSPERFRAME*OFDM_NC*f + i].imag = cimagf(ofdm->rx_np[i]);
            }

            /* note phase/amp ests the same for each col, but check them all anyway */

            for (i = 0; i < OFDM_ROWSPERFRAME; i++) {
                for (j = 0; j < OFDM_NC; j++) {
                    phase_est_pilot_log[OFDM_ROWSPERFRAME*f+i][j] = ofdm->aphase_est_pilot_log[OFDM_NC*i+j];
                    rx_amp_log[OFDM_ROWSPERFRAME*OFDM_NC*f+OFDM_NC*i+j] = ofdm->rx_amp[OFDM_NC*i+j];
                }
            }

            foff_hz_log[f] = ofdm->foff_est_hz;
            timing_est_log[f] = ofdm->timing_est + 1;     /* offset by 1 to match Octave */
            if (f == (logframes-1))
                oct = 0;
        }

	/* if this is in a pipeline, we probably don't want the usual
	   buffering to occur */

        if (fout == stdout) fflush(stdout);
        if (fin == stdin) fflush(stdin);

        f++;
    }

    fclose(fin);
    fclose(fout);

    if (testframes) {
        fprintf(stderr, "BER..: %5.4f Tbits: %5d Terrs: %5d\n", (float)Terrs/Tbits, Tbits, Terrs);
        fprintf(stderr, "BER2.: %5.4f Tbits: %5d Terrs: %5d\n", (float)Terrs2/Tbits2, Tbits2, Terrs2);
    }
    
    /* optionally dump Octave files */

    if (foct != NULL) {
        octave_save_float(foct, "phase_est_pilot_log_c", (float*)phase_est_pilot_log, OFDM_ROWSPERFRAME*NFRAMES, OFDM_NC, OFDM_NC);
        octave_save_complex(foct, "rx_np_log_c", (COMP*)rx_np_log, 1, OFDM_ROWSPERFRAME*OFDM_NC*NFRAMES, OFDM_ROWSPERFRAME*OFDM_NC*NFRAMES);
        octave_save_float(foct, "rx_amp_log_c", (float*)rx_amp_log, 1, OFDM_ROWSPERFRAME*OFDM_NC*NFRAMES, OFDM_ROWSPERFRAME*OFDM_NC*NFRAMES);
        octave_save_float(foct, "foff_hz_log_c", foff_hz_log, NFRAMES, 1, 1);
        octave_save_int(foct, "timing_est_log_c", timing_est_log, NFRAMES, 1);
        fclose(foct);
    }

    ofdm_destroy(ofdm);

    return 0;
}
