Document: codec2
Title: Debian codec2 Manual
Author: <insert document author here>
Abstract: This manual describes what codec2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/codec2/codec2.sgml.gz

Format: postscript
Files: /usr/share/doc/codec2/codec2.ps.gz

Format: text
Files: /usr/share/doc/codec2/codec2.text.gz

Format: HTML
Index: /usr/share/doc/codec2/html/index.html
Files: /usr/share/doc/codec2/html/*.html
