#!/bin/bash
#
# run_tst_ofdm_demod_ideal
#
# This is a short test with a few frames of ideal data (no channel model).
# The output of the stm32 ofdm_demod is expected to match the reference exaclty.

TEST="tst_ofdm_demod_ideal"

# Find the scripts directory
SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Setup common variables
source $SCRIPTS/run_tests_common.sh

# CD to test run dir
cd "${RUN_DIR}"

#######################################
# Test specific code:

# Setup:
if [ ${OPT_SETUP} == true ] ; then

    ofdm_get_test_bits - -f 10 | \
        ofdm_mod - stm_in.raw \
        > setup.log 2>&1

    fi

# Run:
if [ ${OPT_RUN} == true ] ; then
    echo "stm32 code must be run manually at this time"
    read -p "Press enter when the test has been run"
    fi

# Check:
if [ ${OPT_CHECK} == true ] ; then

    ofdm_demod stm_in.raw ref_demod_out.raw \
        -o ofdm_demod_ref_log.txt \
        --testframes \
        > ref_gen.log 2>&1

    # BER:
    grep -q "^BER\.\.*: 0.000" stm_stdout.txt
    if [ $? != 0 ] ; then echo "Failed" ; exit 1 ; fi

    # Output:
    cmp ref_demod_out.raw stm_out.raw > check.log 2>&1
    if [ $? != 0 ] ; then echo "Failed" ; exit 1 ; fi

    echo "Passed"

    fi
