#!/bin/bash
#
# run_tst_ofdm_mod <test_sub_type> [--load]

# Find the scripts directory
SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Setup common variables
source $SCRIPTS/run_tests_common.sh

# Save directory
ORIG_DIR=${PWD}

declare -i Fails=0

#####################################################################
TEST_NAME="tst_ofdm_mod"
TEST_OPT="${TEST}"  # passed in from run_tests_common
LOAD=${ARGS[--load]:+--load}
FULL_TEST_NAME="${TEST_NAME}_${TEST_OPT}"
RUN_DIR="${UNITTEST_BASE}/test_run/${FULL_TEST_NAME}"
echo -e "\n\n${FULL_TEST_NAME}"
setup_common "${RUN_DIR}"
${TEST_NAME}_setup ${TEST_OPT} --clean
cd "${RUN_DIR}" 
run_stm32_prog ${UNITTEST_BIN}/${TEST_NAME}.elf ${LOAD} |& tee gdb.log
${TEST_NAME}_check ${TEST_OPT} |& tee check.log ||
let Fails=($Fails + 1)
cd "${ORIG_DIR}" 

sleep 5 # Delay for st-util to close

if (( $Fails == 0 )); then
    echo -e "\nTest ${FULL_TEST_NAME} PASSED"
else
    echo -e "\nTest ${FULL_TEST_NAME} FAILED!"
fi

exit $Fails

# vi:set ts=4 et sts=4:
