#!/bin/bash
#
# tst_ofdm_demod_setup
#
# Setup input and reference data for one of several versions of this test.

# Find the scripts directory
SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Setup common variables
source $SCRIPTS/run_tests_common.sh

# Prepend the common test name to the extension from the command line
FULL_TEST_NAME="tst_ofdm_demod_${TEST}"

# RUN_DIR - Directory where test will be run
RUN_DIR="${UNITTEST_BASE}/test_run/${FULL_TEST_NAME}"

# Call common setup function to make the directory
setup_common "${FULL_TEST_NAME}"

# Change to test directory
cd "${RUN_DIR}"


#####################################################################
## Test SETUP actions:

case "${TEST}" in

    ideal )
    	# Config is <verbose>, <testframes>, <ldpc_en>, <log_payload_syms>
    	echo "01010000" > stm_cfg.txt
	ofdm_get_test_bits - -f 10 | ofdm_mod - stm_in.raw > setup.log 2>&1
        ofdm_demod stm_in.raw ref_demod_out.raw -o ofdm_demod_ref_log.txt \
        	--testframes > ref_gen_log.txt 2>&1
	;;

    AWGN )
    	# Config is <verbose>, <testframes>, <ldpc_en>, <log_payload_syms>
    	echo "11010000" > stm_cfg.txt
        ofdm_get_test_bits test_bits.raw 10 > setup.log 2>&1
	ofdm_mod test_bits.raw mod_bits.raw >> setup.log 2>&1
        cohpsk_ch mod_bits.raw stm_in.raw -20 -Fs 8000 -f -5 \
	    --raw_dir ${CODEC2_BASE}/raw >> setup.log 2>&1
        ofdm_demod stm_in.raw ref_demod_out.raw -v -o ofdm_demod_ref_log.txt \
        	--testframes > ref_gen_log.txt 2>&1
	;;

    fade )
    	# Config is <verbose>, <testframes>, <ldpc_en>, <log_payload_syms>
    	echo "01010000" > stm_cfg.txt
        ofdm_get_test_bits test_bits.raw 60 > setup.log 2>&1
	ofdm_mod test_bits.raw mod_bits.raw >> setup.log 2>&1
        cohpsk_ch mod_bits.raw stm_in.raw -20 -Fs 8000 -f -5 -fast \
	    --raw_dir ${CODEC2_BASE}/raw >> setup.log 2>&1
        ofdm_demod stm_in.raw ref_demod_out.raw -v -o ofdm_demod_ref_log.txt \
        	--testframes > ref_gen_log.txt 2>&1
	;;

    esac
