#!/bin/bash
#
# run_all_ofdm_tests

declare -i Fails=0

run_tst_ofdm_mod plain --load || Fails+=1
run_tst_ofdm_mod ldpc || Fails+=1

run_tst_ofdm_demod quick --load || Fails+=1
run_tst_ofdm_demod ideal || Fails+=1
run_tst_ofdm_demod AWGN || Fails+=1
run_tst_ofdm_demod fade || Fails+=1
run_tst_ofdm_demod ldpc || Fails+=1
run_tst_ofdm_demod ldpc_AWGN || Fails+=1
run_tst_ofdm_demod ldpc_fade || Fails+=1

if (( $Fails == 0 )); then
    echo -e "\nAll Tests PASSED"
else
    echo -e "\n$Fails Tests FAILED!"
fi

exit $Fails

# vi:set ts=4 et sts=4:
