#!/bin/bash
#
# tst_ofdm_demod_setup
#
# Setup input and reference data for one of several versions of this test.

# Find the scripts directory
SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Setup common variables
source $SCRIPTS/run_tests_common.sh

# Prepend the common test name to the extension from the command line
FULL_TEST_NAME="tst_ofdm_demod_${TEST}"

# RUN_DIR - Directory where test will be run
RUN_DIR="${UNITTEST_BASE}/test_run/${FULL_TEST_NAME}"

# Call common setup function to make the directory
setup_common "${RUN_DIR}"

# Change to test directory
cd "${RUN_DIR}"


#####################################################################
## Test SETUP actions:

case "${TEST}" in

    quick )
    	# Config is <verbose>, <testframes>, <ldpc_en>, <log_payload_syms> <profile>
    	echo "01010000" > stm_cfg.txt
	ofdm_mod /dev/zero stm_in.raw --testframes 10 > setup.log 2>&1
        ofdm_demod stm_in.raw ref_demod_out.raw -o ofdm_demod_ref_log.txt \
        	--testframes > ref_gen_log.txt 2>&1
	;;

    ideal )
    	# Config is <verbose>, <testframes>, <ldpc_en>, <log_payload_syms> <profile>
    	echo "01010000" > stm_cfg.txt
	ofdm_mod /dev/zero stm_in.raw --testframes 10 > setup.log 2>&1
        ofdm_demod stm_in.raw ref_demod_out.raw -o ofdm_demod_ref_log.txt \
        	--testframes > ref_gen_log.txt 2>&1
	;;

    AWGN )
    	# Config is <verbose>, <testframes>, <ldpc_en>, <log_payload_syms> <profile>
    	echo "01010000" > stm_cfg.txt
	ofdm_mod /dev/zero mod_bits.raw --testframes 10 > setup.log 2>&1
        cohpsk_ch mod_bits.raw stm_in.raw -20 -Fs 8000 -f -5 \
	    --raw_dir ${CODEC2_BASE}/raw >> setup.log 2>&1
        ofdm_demod stm_in.raw ref_demod_out.raw -v -o ofdm_demod_ref_log.txt \
        	--testframes > ref_gen_log.txt 2>&1
	;;

    fade )
    	# Config is <verbose>, <testframes>, <ldpc_en>, <log_payload_syms> <profile>
    	echo "01010000" > stm_cfg.txt
	ofdm_mod /dev/zero mod_bits.raw --testframes 60 > setup.log 2>&1
        cohpsk_ch mod_bits.raw stm_in.raw -24 -Fs 8000 -f -10 -fast \
	    --raw_dir ${CODEC2_BASE}/raw >> setup.log 2>&1
        ofdm_demod stm_in.raw ref_demod_out.raw -v -o ofdm_demod_ref_log.txt \
        	--testframes > ref_gen_log.txt 2>&1
	;;

    profile )
    	# Config is <verbose>, <testframes>, <ldpc_en>, <log_payload_syms> <profile>
    	echo "00001000" > stm_cfg.txt
	ofdm_mod /dev/zero mod_bits.raw --testframes 100 > setup.log 2>&1
        cohpsk_ch mod_bits.raw stm_in.raw -20 -Fs 8000 -f -10 -fast \
	    --raw_dir ${CODEC2_BASE}/raw >> setup.log 2>&1
        ofdm_demod stm_in.raw ref_demod_out.raw -v -o ofdm_demod_ref_log.txt \
        	--testframes > ref_gen_log.txt 2>&1
	;;

    ldpc )
    	# Config is <verbose>, <testframes>, <ldpc_en>, <log_payload_syms> <profile>
    	echo "01110000" > stm_cfg.txt
	ofdm_mod /dev/zero stm_in.raw --testframes 10 --ldpc > setup.log 2>&1
        ofdm_demod stm_in.raw ref_demod_out.raw -o ofdm_demod_ref_log.txt \
        	--testframes --ldpc > ref_gen_log.txt 2>&1
	;;

    ldpc_AWGN )
    	# Config is <verbose>, <testframes>, <ldpc_en>, <log_payload_syms> <profile>
    	echo "01110000" > stm_cfg.txt
	ofdm_mod /dev/zero mod_bits.raw --testframes 30 --ldpc > setup.log 2>&1
        cohpsk_ch mod_bits.raw stm_in.raw -20 -Fs 8000 -f -10 \
	    --raw_dir ${CODEC2_BASE}/raw >> setup.log 2>&1
        ofdm_demod stm_in.raw ref_demod_out.raw -v -o ofdm_demod_ref_log.txt \
        	--testframes --ldpc > ref_gen_log.txt 2>&1
	;;

    ldpc_fade )
    	# Config is <verbose>, <testframes>, <ldpc_en>, <log_payload_syms> <profile>
    	echo "01110000" > stm_cfg.txt
	ofdm_mod /dev/zero mod_bits.raw --testframes 120 --ldpc > setup.log 2>&1
        cohpsk_ch mod_bits.raw stm_in.raw -24 -Fs 8000 -f -10 -fast \
	    --raw_dir ${CODEC2_BASE}/raw >> setup.log 2>&1
        ofdm_demod stm_in.raw ref_demod_out.raw -v -o ofdm_demod_ref_log.txt \
        	--testframes --ldpc > ref_gen_log.txt 2>&1
	;;

    esac
