#!/bin/bash
#
# tst_codec2_enc_check
#
# Setup input and reference data for one of several versions of this test.

# Find the scripts directory
SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Setup common variables
source $SCRIPTS/run_tests_common.sh

# RUN_DIR - Directory where test will be run
RUN_DIR="${UNITTEST_BASE}/test_run/${FULL_TEST_NAME}"

# Call common setup function to make the directory
setup_common "${RUN_DIR}"

# Change to test directory
cd "${RUN_DIR}"


#####################################################################
## Test CHECK actions:

declare -i Fails=0

case "${TEST_OPT}" in
    1600)
	echo -e "\nMust manually listen to this!"
	c2dec 1600 stm_out.raw stm_dec.raw
	aplay -f S16_LE stm_dec.raw
    	;;
    700C)
	echo -e "\nMust manually listen to this!"
	c2dec 700C stm_out.raw stm_dec.raw
	aplay -f S16_LE stm_dec.raw
    	;;
    esac


if (( $Fails == 0 )); then
    echo -e "\nTest PASSED"
else
    echo -e "\nTest FAILED!"
fi


exit $Fails
