/*---------------------------------------------------------------------------*\
                                                                             
  FILE........: test_cohpsk_ch.c
  AUTHOR......: David Rowe  
  DATE CREATED: April 2015
                                                                             
  Tests for the C version of the coherent PSK FDM modem with channel
  impairments generated by Octave.
                                                                             
\*---------------------------------------------------------------------------*/

/*
  Copyright (C) 2015 David Rowe

  All rights reserved.

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License version 2, as
  published by the Free Software Foundation.  This program is
  distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or
  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
  License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with this program; if not, see <http://www.gnu.org/licenses/>.
*/

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "codec2_cohpsk.h"
#include "test_bits_coh.h"
#include "octave.h"
#include "comp_prim.h"
#include "noise_samples.h"

#define FS          8000
#define FRAMES      100
#define FOFF_HZ     10.5
#define ES_NO_DB     8.0
#define HF_DELAY_MS  2.0
#define HF_GAIN      1.423599

#define FADING_FILE_NAME "../../raw/fading_samples.float"

int main(int argc, char *argv[])
{
    struct COHPSK *coh;
    int            tx_bits[COHPSK_BITS_PER_FRAME];
    COMP           tx_fdm[COHPSK_SAMPLES_PER_FRAME];
    COMP           ch_fdm[COHPSK_SAMPLES_PER_FRAME];
    int            rx_bits[COHPSK_BITS_PER_FRAME];
                                            
    int            f, r, i;
    int           *ptest_bits_coh, *ptest_bits_coh_end, *ptest_bits_coh_rx;
    COMP           phase_ch;
    int            noise_r, noise_end;
    int            errors;
    int            state, next_state, nerrors, nbits, reliable_sync_bit;
    float          EsNo, variance;
    COMP           scaled_noise;
    float          EsNodB, foff_hz;
    int            fading_en, nhfdelay, ret;
    COMP          *ch_fdm_delay, aspread, aspread_2ms, delayed, direct;
    FILE          *ffading;

    EsNodB = ES_NO_DB;
    foff_hz =  FOFF_HZ;
    if (argc == 4) {
        EsNodB = atof(argv[1]);
        foff_hz = atof(argv[2]);
        fading_en = atoi(argv[3]);
    }
    fprintf(stderr, "EsNodB: %4.2f foff: %4.2f Hz fading: %d\n", EsNodB, foff_hz, fading_en);

    coh = cohpsk_create();
    assert(coh != NULL);

    ptest_bits_coh = ptest_bits_coh_rx = (int*)test_bits_coh;
    ptest_bits_coh_end = (int*)test_bits_coh + sizeof(test_bits_coh)/sizeof(int);
    phase_ch.real = 1.0; phase_ch.imag = 0.0; 
    noise_r = 0; 
    noise_end = sizeof(noise)/sizeof(COMP);
    
    /*  each carrier has power = 2, total power 2Nc, total symbol rate
        NcRs, noise BW B=Fs Es/No = (C/Rs)/(N/B), N = var =
        2NcFs/NcRs(Es/No) = 2Fs/Rs(Es/No) */

    EsNo = pow(10.0, EsNodB/10.0);
    variance = 2.0*COHPSK_FS/(COHPSK_RS*EsNo);

    /* init HF fading model */

    if (fading_en) {
        ffading = fopen(FADING_FILE_NAME, "rb");
        if (ffading == NULL) {
            printf("Can't find fading file: %s\n", FADING_FILE_NAME);
            exit(1);
        }
        nhfdelay = floor(HF_DELAY_MS*FS/1000);
        ch_fdm_delay = (COMP*)malloc((nhfdelay+COHPSK_SAMPLES_PER_FRAME)*sizeof(COMP));
        assert(ch_fdm_delay != NULL);
        for(i=0; i<nhfdelay+COHPSK_SAMPLES_PER_FRAME; i++) {
            ch_fdm_delay[i].real = 0.0;
            ch_fdm_delay[i].imag = 0.0;
        }
    }

    /* Main Loop ---------------------------------------------------------------------*/

    for(f=0; f<FRAMES; f++) {
        
	/* --------------------------------------------------------*\
	                          Mod
	\*---------------------------------------------------------*/

        memcpy(tx_bits, ptest_bits_coh, sizeof(int)*COHPSK_BITS_PER_FRAME);
        ptest_bits_coh += COHPSK_BITS_PER_FRAME;
        if (ptest_bits_coh >= ptest_bits_coh_end) {
            ptest_bits_coh = (int*)test_bits_coh;
        }

	cohpsk_mod(coh, tx_fdm, tx_bits);

	/* --------------------------------------------------------*\
	                          Channel
	\*---------------------------------------------------------*/

        fdmdv_freq_shift(ch_fdm, tx_fdm, foff_hz, &phase_ch, COHPSK_SAMPLES_PER_FRAME);

        /* optional HF fading -------------------------------------*/

        if (fading_en) {

            /* update delayed signal buffer */

            for(i=0; i<nhfdelay; i++)
                ch_fdm_delay[i] = ch_fdm_delay[i+COHPSK_SAMPLES_PER_FRAME];
            for(; i<COHPSK_SAMPLES_PER_FRAME; i++)
                ch_fdm_delay[i] = ch_fdm[i];

            /* combine direct and delayed paths, both multiplied by
               "spreading" (doppler) functions */

            for(i=0; i<COHPSK_SAMPLES_PER_FRAME; i++) {
                ret = fread(&aspread, sizeof(COMP), 1, ffading);
                assert(ret == 1);
                ret = fread(&aspread_2ms, sizeof(COMP), 1, ffading);
                assert(ret == 1);
                //printf("%f %f %f %f\n", aspread.real, aspread.imag, aspread_2ms.real, aspread_2ms.imag);
                
                direct    = cmult(aspread, ch_fdm[i]);
                delayed   = cmult(aspread_2ms, ch_fdm_delay[i]);
                ch_fdm[i] = fcmult(HF_GAIN, cadd(direct, delayed));
            }
        }

        /* AWGN noise ------------------------------------------*/

        for(r=0; r<COHPSK_SAMPLES_PER_FRAME; r++) {
            scaled_noise = fcmult(sqrt(variance), noise[noise_r]);
            ch_fdm[r] = cadd(ch_fdm[r], scaled_noise);
            noise_r++;
            if (noise_r > noise_end)
                noise_r = 0;
        }

	/* --------------------------------------------------------*\
	                          Demod
	\*---------------------------------------------------------*/

 	cohpsk_demod(coh, rx_bits, &reliable_sync_bit, ch_fdm);

        errors = 0;
        for(i=0; i<COHPSK_BITS_PER_FRAME; i++) {
            errors += (rx_bits[i] & 0x1) ^ ptest_bits_coh_rx[i];
        }

        /* state logic to sync up to test data */

        next_state = state;

        if (state == 0) {
            if (reliable_sync_bit && (errors == 0)) {
                next_state = 1;
                ptest_bits_coh_rx += COHPSK_BITS_PER_FRAME;
                nerrors = errors;
                nbits = COHPSK_BITS_PER_FRAME;
                fprintf(stderr, "  test data sync\n");            

            }
        }

        if (state == 1) {
            nerrors += errors;
            nbits   += COHPSK_BITS_PER_FRAME;
            ptest_bits_coh_rx += COHPSK_BITS_PER_FRAME;
            if (ptest_bits_coh_rx >= ptest_bits_coh_end) {
                ptest_bits_coh_rx = (int*)test_bits_coh;
            }
        }

        state = next_state;
    }
    
    printf("%4.3f %d %d\n", (float)nerrors/nbits, nbits, nerrors);

    if (fading_en) {
        free(ch_fdm_delay);
        fclose(ffading);
    }
    cohpsk_destroy(coh);

    return 0;
}

