/* Generated by write_pilot_file() Octave function */

#define NSYMROW      20   /* number of data symbols for each row (i.e. each carrier) */
#define NS           4   /* number of data symbols between pilots                   */
#define NP           2   /* number of pilots to use for channel est                 */
#define NPILOTSFRAME 5   /* number of pilot symbols of each row                     */
#define PILOTS_NC    4   /* number of carriers in coh modem                         */

#define NSYMROWPILOT 25   /* length of row after pilots inserted                     */

