/*
  FILE....: H_212_158.h

  Static arrays for LDPC codec H_212_158, generated by ldpc_gen_c_h_file.m.
*/

#define H_212_158_NUMBERPARITYBITS 56
#define H_212_158_MAX_ROW_WEIGHT 14
#define H_212_158_CODELENGTH 212
#define H_212_158_NUMBERROWSHCOLS 156
#define H_212_158_MAX_COL_WEIGHT 8
#define H_212_158_DEC_TYPE 0
#define H_212_158_MAX_ITER 100

extern const uint16_t H_212_158_H_rows[];
extern const uint16_t H_212_158_H_cols[];
